### ISSUE TITLE
Adding favicon icon 

### ISSUE THREAD

**Issue by Harsh3363** [shreya024/MemoriesApp#1]
The current icon is React default icon which if changed can give a better impression of the website also the name can be changed 

![Screenshot (88)_LI](https://user-images.githubusercontent.com/72756692/182011838-d953fbf5-ad88-4f15-8cb7-cdb97b41fab3.jpg)

**Comment by Harsh3363** [comment]
Hii @shreya024  please assign this to me I would like to make the changes for better User experience

**Comment by RohithBoppey** [comment]
Hey @Harsh3363, are you still working on it? I would like to choose an appropriate Favicon and update it. Can I keep a PR too?

**Comment by Harsh3363** [comment]
> Hey @Harsh3363, are you still working on it? I would like to choose an appropriate Favicon and update it. Can I keep a PR too?

Sorry but I'm working on this.
