### ISSUE TITLE
User Profile Frontend

### ISSUE THREAD

**Issue by soumali28** [shreya024/MemoriesApp#10]

**Comment by prateekch33** [comment]
Hi, can I be assigned to this?

**Comment by fykaa** [comment]
@prateekch33 You assigned for the issue namely User Profile Frontend. You may start contributions🎉

**Comment by shreya024** [comment]
> Hi, can I be assigned to this?

@prateekch33 Any updates?

**Comment by prateekch33** [comment]
Ya I will going to create a PR by tonight

**Comment by prateekch33** [comment]
Due to some important college work, I'm not getting the time to complete it. You can reassign this to someone else. Sorry for the inconvenience caused.

**Comment by nobel10122025** [comment]
can i work on this ? i am good at react.

**Comment by nobel10122025** [comment]
please provide me with some discription if possbile about that page.
It would be of great help!!

**Comment by nobel10122025** [comment]
please provide me with some description if possible about that page.
It would be of great help!!

**Comment by shreya024** [comment]
> please provide me with some description if possible about that page. It would be of great help!!

Sure it will contain Name,UserName,ProfilePic,Cover photo,no. of posts,followers,following etc...you can take inspiration from here https://dribbble.com/shots/10670840-User-Profile-UI-Component

followed by the posts/timeline of that user https://dribbble.com/shots/5715151-Facebook-user-profile-concept-white-version

Keep the css style similar to login/loading page(try neomorphism or glassmorphism)

**Comment by nobel10122025** [comment]
Thank you. Sure

**Comment by nobel10122025** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/48177682/184479933-478d7060-959a-48e4-8da6-032aaff30867.png">

i have completed making the card. but i haven't attended any kind of functionality. Its completely static now and i have just included the <Posts/> in the UserProfile component. should i redesign the post sections as well?

**Comment by nobel10122025** [comment]
I have completed making the card. but i haven't attached any kind of functionality. It's completely static now and i have just included the <Posts /> in the UserProfile component. should i redesign the posts sections as well?

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/48177682/184480343-d298a906-421e-4913-b9a6-820d29c9312d.png">

**Comment by shreya024** [comment]
> I have completed making the card. but i haven't attached any kind of functionality. It's completely static now and i have just included the in the UserProfile component. should i redesign the posts sections as well?
> 
> <img alt="image" width="1433" src="https://user-images.githubusercontent.com/48177682/184480343-d298a906-421e-4913-b9a6-820d29c9312d.png">

@nobel10122025 Try changing the background similar(not exactly same) to the style of login page and add a small About Section. No need to redesign the posts section just include them with a timeline header below this.

**Comment by nobel10122025** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/48177682/184496889-a0de835c-ce2a-4b59-9b89-241c6c458738.png">

Mobile View
<img width="317" alt="image" src="https://user-images.githubusercontent.com/48177682/184496909-80f5f379-f2ec-48a0-a84a-0ff06f5740a7.png">

It is completely responsive.

If there are any changes please let me know..
and thank you for assigning me this issue.

**Comment by shreya024** [comment]
LGTM! You could make a PR and get reviewed :)
