### ISSUE TITLE
Implement Form Validation

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#12]
validate form entries

**Comment by souravbhunia07** [comment]
Heyy can I implement this functionality. please assign it to me.

**Comment by shreya024** [comment]
> Heyy can I implement this functionality. please assign it to me.

Assigned Issue #11.You may start contributing there

**Comment by codingmickey** [comment]
I can work on it

**Comment by fykaa** [comment]
Hi @codingmickey If this issue is completed, kindly close this issue :)
