### ISSUE TITLE
Dark Mode Implementation

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#17]
Add a toggle button and custom css for light and dark mode

**Comment by thisisamanmishra** [comment]
Assign this to me

**Comment by thisisamanmishra** [comment]
@shreya024 Give me 2 more days due to my College exams I'm late

**Comment by mridulpal019** [comment]
hi! i would like to work on this issue 
kindly assign it to me

**Comment by Debdeep1** [comment]
Go ahead @mridulpal019 and try to finish it on time.

**Comment by shreya024** [comment]
> hi! i would like to work on this issue kindly assign it to me @shreya024

Any updates?

**Comment by mridulpal019** [comment]
Ya I'm working on it   I will make the said changes by this weekend.

**Comment by mridulpal019** [comment]
@shreya024 made a PR #72 kindly review it .
