### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#2]
Add a loading Screen with animation and logo

**Comment by Himanshu-370** [comment]
hey, can I be assigned to this issue?

**Comment by tejas910** [comment]
hi can i  assigned to this issue

**Comment by tejas910** [comment]
Name: Tejas Patil
Github link:- https://github.com/tejas910
Email Id: tppatil910@gmail.com
Approach: To enhance loading page of app.
role: contributor

**Comment by soumali28** [comment]
@tejas910 Hey tejas this issue is already assigned we will be coming with new issues u can contribute in them
