### ISSUE TITLE
Create the footer 

### ISSUE THREAD

**Issue by soumali28** [shreya024/MemoriesApp#20]

**Comment by Himanshu-370** [comment]
Assign me

**Comment by AnushkaMittal21** [comment]
Please assign me this issue.

**Comment by Jhanvi528** [comment]
@Himanshu-370 Go ahead

**Comment by SushantPatial** [comment]
I asked on discord to create this issue so I can work on this. Please assign it to me

**Comment by shreya024** [comment]
> I asked on discord to create this issue so I can work on this. Please assign it to me

Assigned #22 to you
