### ISSUE TITLE
Navbar Implementation

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#29]
Maintain the style of footer and loading page ...elements to include
1.Button for Sidebar Drawer
2.Logo
3.Searchbar (in middle)
4.Sign In button(extreme right)

**Comment by SushantPatial** [comment]
I'd like to work on this

**Comment by soumali28** [comment]
@SushantPatial  are you an SSOC participant?

**Comment by AnushkaMittal21** [comment]
Can I work on it? I am a SSOC participant.

**Comment by YasirObaibullah99** [comment]
Can I work in it as I am in SSOC also

**Comment by SushantPatial** [comment]
> @SushantPatial are you an SSOC participant?

Yes I am
