### ISSUE TITLE
Background Themes

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#30]
Button to change background themes from some predefined themes(images - can take from free images)
Button placement : bottom left corner

**Comment by Himanshu-370** [comment]
Assign me

**Comment by Sampurankishoresrivastava** [comment]
Heyy can I implement this . please assign it to me.

**Comment by Susmita-Dey** [comment]
@Himanshu-370 Go ahead

**Comment by shreya024** [comment]
> Assign me

Select at least 10 different ones from here https://www.freepik.com/search?format=search&query=travel+sky+landscape&type=photo&referer=detail&page=2

**Comment by shreya024** [comment]
@Himanshu-370 Any updates?

**Comment by Himanshu-370** [comment]
Actually I moved to college yesterday 
So need some time to settle down
It may take sometime, so you can assign it to someone else

**Comment by Sampurankishoresrivastava** [comment]
Thank you for assigning, Looking forward to work on it.

**Comment by shreya024** [comment]
> Thank you for assigning, Looking forward to work on it.

Any updates?

**Comment by SahilDahekar** [comment]
@shreya024 can i take up this issue ?

**Comment by shreya024** [comment]
> @shreya024 can i take up this issue ?

Sure due to inactivity ,Issue has been reassigned to you
