### ISSUE TITLE
BookMark Implementation

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#37]
Implement a bookmark button to save the bookmarked memories

**Comment by prakhar728** [comment]
Hey, I would like to work on this. Please assign this to me. I am a SSOC partcipant.

**Comment by prakhar728** [comment]
Hey regarding this issue it's in three parts.

- [x] Add the server side routes
- [ ] Add a button in the Posts UI to add them to the Bookmarks list
- [ ] View all the Bookmarked posts.

I resolved the first part. So should I make three separate PRs for each? I think we could divide it into two issues. 
I don't handle the UI part well so someone can make the bookmarks page.

**Comment by shreya024** [comment]
> Hey regarding this issue it's in three parts.
> 
> * [x]  Add the server side routes
> * [ ]  Add a button in the Posts UI to add them to the Bookmarks list
> * [ ]  View all the Bookmarked posts.
> 
> I resolved the first part. So should I make three separate PRs for each? I think we could divide it into two issues. I don't handle the UI part well so someone can make the bookmarks page.

Okay @prakhar728 , #52 created for the UI part :)
