### ISSUE TITLE
Implement Backend for Users

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#41]
Implement the backend for users having various params like id,posts,messages,notifications etc.

**Comment by codingmickey** [comment]
We need to just to create a User model and some routes for login and signup right?

**Comment by shreya024** [comment]
> We need to just to create a User model and some routes for login and signup right?

Yes,this is just to create User model with various params like id,posts,messages,notifications etc. #5 is for implementing the login/signup

**Comment by codingmickey** [comment]
Ok, I can work on this issue

**Comment by Debdeep1** [comment]
@codingmickey assigned

**Comment by prakhar728** [comment]
Hey. Has this been done? If not then will it be reassigned?

**Comment by Debdeep1** [comment]
It will be reassigned if the previous assignee is unable to do it.
If you can complete this task then you can comment here and we will update you, once we get response from the admin.

**Comment by shreya024** [comment]
> Hey. Has this been done? If not then will it be reassigned?



> Hey. Has this been done? If not then will it be reassigned?

Sure @Debdeep1 you can reassign to @prakhar728 if no replies from @codingmickey

**Comment by codingmickey** [comment]
I have completed it will pr by tonight, sorry for not updating

**Comment by Debdeep1** [comment]
@codingmickey have you finished yet?
