### ISSUE TITLE
Posts UI improvement

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#46]
Improve the UI of each post...include some 3D effects and maintain the style as per loading page

**Comment by Himanshu-370** [comment]
Assign me!

**Comment by Debdeep1** [comment]
@Himanshu-370  go ahead

**Comment by shreya024** [comment]
> Assign me!

Any updates?

**Comment by fykaa** [comment]
@Debdeep1 We received no updates, hence considering reassignment.

**Comment by fykaa** [comment]
@Himanshu-370 We received no updates, hence considering reassignment.

**Comment by SahilDahekar** [comment]
hey can i work on this issue

**Comment by shreya024** [comment]
> @shreya024 @Debdeep1 hey can i work on this issue

Sure, go ahead!

**Comment by Debdeep1** [comment]
sorry for being a bit inactive...had some assignments...anyways..try to finish this task within time. We have alot of issues left, to work on.
