### ISSUE TITLE
Messages page UI

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#50]
Develop a an interactive UI for the Messages page

**Comment by SahilDahekar** [comment]
- Hey can i work on this issue ?
- Also plz provide some description and screenshots if possible

**Comment by Debdeep1** [comment]
@SahilDahekar go ahead..check discord grp for references..if any

**Comment by shreya024** [comment]
> * Hey can i work on this issue ?
> * Also plz provide some description and screenshots if possible

You can take inspirations from here https://dribbble.com/shots/17564412-Dashboard-messaging-Untitled-UI and keep the style similar as login page

**Comment by SahilDahekar** [comment]
okay

**Comment by SahilDahekar** [comment]
my college started this week so couldnt get time but ill be taking the issue today and will hopfully complete it till sunday

**Comment by Debdeep1** [comment]
Please try to complete it by Sunday, latest.

**Comment by SahilDahekar** [comment]
Yes

**Comment by SahilDahekar** [comment]
<img width="214" alt="Screenshot 2022-08-21 235436" src="https://user-images.githubusercontent.com/97726887/185904147-fd0ad4ee-84dd-49d7-a52c-52456a7676c7.png">
<img width="941" alt="Screenshot 2022-08-21 235339" src="https://user-images.githubusercontent.com/97726887/185904157-2121d2dd-8e6a-495c-930d-b6f770afb6fc.png">
need a little more time to work on mobile responsiveness and toggle function
