### ISSUE TITLE
Routes README

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#54]
Add a README in the client folder regarding all the routes developed so far and their functions

**Comment by nobel10122025** [comment]
can i work on this ? i am good at react.

**Comment by prakhar728** [comment]
One could copy paste the Readme file I created in the server side? Should I do this?

**Comment by shreya024** [comment]
> One could copy paste the Readme file I created in the server side? Should I do this?

More routes have been added at server side regarding user and some pages added on client side like /login etc

**Comment by prakhar728** [comment]
I'd like to complete this. Can you assign it to me?
