### ISSUE TITLE
Form Layout Enhancement

### ISSUE THREAD

**Issue by shreya024** [shreya024/MemoriesApp#7]
Change the layout of the form keeping the content same ,enhance using css and give it more width than height (Maybe try using a Modal)

**Comment by AnshuMishra01** [comment]
![image](https://user-images.githubusercontent.com/95041038/182773571-fced2054-693b-45b8-be00-940594b46de6.png)
Are you talking about this form?

**Comment by AnshuMishra01** [comment]
I can do this I had designed plenty of forms :)

**Comment by Debdeep1** [comment]
Okay, assigning to AnshuMishra01

**Comment by shreya024** [comment]
> ![image](https://user-images.githubusercontent.com/95041038/182773571-fced2054-693b-45b8-be00-940594b46de6.png) Are you talking about this form?

Yes

**Comment by AnshuMishra01** [comment]
Does anyone check it? I had edited the form design:)
